from PIL import Image
img = Image.open("lince.JPG")
box = (200, 200, 400, 400)
region = img.crop(box)
region.save('crop.JPG')
region.show()
img2 = Image.open("crop.JPG")
blackAndWhite = img2.convert("L")
blackAndWhite.save('crop2.JPG')
blackAndWhite.show()